#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: GPL-3.0-only

# shellcheck disable=SC2034 # consumed by /etc/rc.common
START=99
# shellcheck disable=SC2034 # consumed by /etc/rc.common
STOP=1
# shellcheck disable=SC2034 # consumed by /etc/rc.common
USE_PROCD=1

PROG=/usr/bin/gl-tailscale-cert

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" --daemon
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 0
	procd_set_param stderr 0
	procd_close_instance
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger ts_cert
}
